steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']  # This depends on your build setup
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
